### ISSUE TITLE
Code Injection in Peer Alias

### ISSUE THREAD

**Issue by schulzemic** [cryptosharks131/lndg#363]
I have a channel with a node that has the following alias: `<script>alert(\"LDK\");</script>`

On the lndg overview page, the alias field just remains empty. But when I click on the channel ID in the list of active channels, an alert pops up.

**Comment by JaviLib** [comment]
I accidentally created a duplicate: https://github.com/cryptosharks131/lndg/issues/394
Anyway mine is better explained with images.

Almost 9 months after this, we are still waiting for a patch. This software seems to be adandonware at this point.

**Comment by cryptosharks131** [comment]
This should now be resolved in the latest `v1.9.0` branch. Can you verify if you are still able to replicate the issue with this branch?

**Comment by JaviLib** [comment]
It is not solved:

<img width="495" alt="imagen" src="https://github.com/user-attachments/assets/8ab551a6-8183-4cac-bd0c-1ce21b8fddcd">

LNDg v1.9.0

**Comment by cryptosharks131** [comment]
For now, focused on the alert that is generated from the example script execution but not that it is still displayed properly.

Do you also still see the alert being generated?

**Comment by JaviLib** [comment]
No, the alert in the channel is not happening anymore.
