### ISSUE TITLE
Node name is added on every restart

### ISSUE THREAD

**Issue by LupusPluvia** [cryptosharks131/lndg#435]
Recently, my Nodn name and public key are displayed anew every time I restart; a new line is added each time.

Can someone help me?

![Image](https://github.com/user-attachments/assets/b794bc89-7123-4f74-a8d4-d83134a0a3c6)
](url)

**Comment by Spindler360** [comment]
Same here. I think it's a bug in the Lightning Wallet for Umbrel. Are you using Umbrel? Then you should have a similar image in the wallet under Node ID.
Maybe @nmfretz or someone else can help. You can also report your error at https://github.com/getumbrel/umbrel-lightning 

I suspect that it is incorrectly assumed that the Tor address has changed every time it is started. 
With externalip in lnd.conf for clearnet, the problem does not occur.

@cryptosharks131: From which file are the lnd URIs for lndg (umbrel) read? 

Best regards

**Comment by cryptosharks131** [comment]
This issue is due to a bug in LND `v0.20.0` and this duplication can even be seen when running the `lncli getinfo` command. LNDg is just displaying the resultts from a grpc call of getinfo.

The issue is fixed with the most recent LND release `v0.20.1` version.
https://github.com/lightningnetwork/lnd/blob/v0.20.x-branch/docs/release-notes/release-notes-0.20.1.md#bug-fixes

**Comment by LupusPluvia** [comment]
![Image](https://github.com/user-attachments/assets/965cb412-933c-425f-8f77-fc674efe3fa3)

I have version v1.10.1 and the problem still exists.

**Comment by Spindler360** [comment]
> I have version v1.10.1 and the problem still exists.

LND ≠ LNDg 😉

**Comment by LupusPluvia** [comment]
LNDG

**Comment by LupusPluvia** [comment]
lnd is 0.20.0 beta

**Comment by Spindler360** [comment]
> This issue is due to a bug in **LND** `v0.20.0`

You wrote about LND**g**. There is no Bug in LNDg. It's in LND. Please follow the Link from cryptosharks131 above. 

> The issue is fixed with the most recent LND release v0.20.1 version.

In short: We must wait für LND Update for OS like Start9, Umbrel etc.

**Comment by LupusPluvia** [comment]
Okay, thank you.

**Comment by LupusPluvia** [comment]
How long will it take?

**Comment by Spindler360** [comment]
LND v0.20.1-beta was released on February 12, 2026, for common server platforms such as Linux and Windows.
For specific operating systems such as Start9 or Umbrel it's hard to guess. 
I hope it won't take too much longer. We'll see when the update button lights up. 🍵

**Comment by LupusPluvia** [comment]
Yep, then it means waiting and drinking tea.

**Comment by LupusPluvia** [comment]
![Image](https://github.com/user-attachments/assets/5325f45c-4cbb-443b-910b-fe773ddb84a6)Do they mean that?
